# app/models/permissions.py
from sqlalchemy import Column, Text, ForeignKey, text
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import relationship
import uuid

from app.db.base_class import Base


class Permissions(Base):
    """
    SQLAlchemy model for permissions (permissions) table.

    Columns:
      - permission_id   : uuid, not null, default uuid_generate_v4()
      - auth_action_id  : uuid, not null (FK -> auth_actions.auth_action_id)
      - resource_id     : uuid, not null (FK -> resources.resource_id)
    """

    __tablename__ = "permissions"

    permission_id = Column(
        UUID(as_uuid=True),
        primary_key=True,
        nullable=False,
        server_default=text("uuid_generate_v4()"),
        doc="Primary key UUID (generated by Postgres uuid_generate_v4())",
    )

    auth_action_id = Column(
        UUID(as_uuid=True),
        ForeignKey("auth_actions.auth_action_id", ondelete="CASCADE"),
        nullable=False,
        doc="FK to auth_actions.auth_action_id",
    )

    resource_id = Column(
        UUID(as_uuid=True),
        ForeignKey("resources.resource_id", ondelete="CASCADE"),
        nullable=False,
        doc="FK to resources.resource_id",
    )

    # -------------
    # Relationships
    # -------------
    
    auth_action = relationship("AuthActions", back_populates="permission")
    resource = relationship("Resource", back_populates="permission")

    role_permission = relationship("RolePermissions", back_populates="permission")

    def __repr__(self) -> str:
        return (
            f"<Permissions(permission_id={self.permission_id!r}, auth_action_id={self.auth_action_id!r}, "
            f"resource_id={self.resource_id!r})>"
        )
