# app/models/person_team.py
from sqlalchemy import Column, Text, Date, ForeignKey, text
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import relationship
import uuid

from app.db.base_class import Base


class PersonTeam(Base):
    """
    SQLAlchemy model for person_team (player_team) table.

    Columns:
      - pt_id           : uuid, not null, default uuid_generate_v4()
      - team_id         : uuid, not null (FK -> team.team_id)
      - person_id       : uuid, not null (FK -> person.person_id)
      - person_type     : text, not null  (CHECK: Coach | Player)
      - start_date      : date
      - end_date        : date
      - transfer_reason : text
      - status          : text
      - pt_pic          : text
    """

    __tablename__ = "person_team"

    pt_id = Column(
        UUID(as_uuid=True),
        primary_key=True,
        nullable=False,
        server_default=text("uuid_generate_v4()"),
        doc="Primary key UUID (generated by Postgres uuid_generate_v4())",
    )

    team_id = Column(
        UUID(as_uuid=True),
        ForeignKey("team.team_id", ondelete="CASCADE"),
        nullable=False,
        doc="FK to team.team_id",
    )

    person_id = Column(
        UUID(as_uuid=True),
        ForeignKey("person.person_id", ondelete="CASCADE"),
        nullable=False,
        doc="FK to person.person_id",
    )

    person_type = Column(
        Text(),
        nullable=False,
        doc="Role type (Coach or Player)",
    )

    start_date = Column(Date(), nullable=True)
    end_date = Column(Date(), nullable=True)

    transfer_reason = Column(Text(), nullable=True)
    status = Column(Text(), nullable=True)
    pt_pic = Column(Text(), nullable=True)

    # -------------
    # Relationships
    # -------------
    
    team = relationship("Team", back_populates="person_teams")
    person = relationship("Person", back_populates="person_teams")

    participations = relationship(
        "PersonParticipation",
        back_populates="person_team",
        cascade="all, delete-orphan"
    )

    def __repr__(self) -> str:
        return (
            f"<PersonTeam(pt_id={self.pt_id!r}, team_id={self.team_id!r}, "
            f"person_id={self.person_id!r}, person_type={self.person_type!r})>"
        )
