# app/models/person_participation.py
from sqlalchemy import Column, Text, ForeignKey, text
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import relationship
import uuid

from app.db.base_class import Base


class PersonParticipation(Base):
    """
    SQLAlchemy model for person_participation table.

    Columns:
      - pp_id  : uuid, not null, default uuid_generate_v4()
      - pt_id  : uuid, not null (FK -> person_team.pt_id)
      - tt_id  : uuid, not null (FK -> team_tournament.tt_id)
      - pp_pic : text
    """

    __tablename__ = "person_participation"

    pp_id = Column(
        UUID(as_uuid=True),
        primary_key=True,
        nullable=False,
        server_default=text("uuid_generate_v4()"),
        doc="Primary key UUID (generated by Postgres uuid_generate_v4())",
    )

    pt_id = Column(
        UUID(as_uuid=True),
        ForeignKey("person_team.pt_id", ondelete="CASCADE"),
        nullable=False,
        doc="FK to person_team.pt_id",
    )

    tt_id = Column(
        UUID(as_uuid=True),
        ForeignKey("team_tournament.tt_id", ondelete="CASCADE"),
        nullable=False,
        doc="FK to team_tournament.tt_id",
    )

    pp_pic = Column(Text(), nullable=True)

    # Relationships
    person_team = relationship(
        "PersonTeam",
        back_populates="participations"
    )

    team_tournament = relationship(
        "TeamTournament",
        back_populates="person_participations"
    )
    def __repr__(self) -> str:
        return f"<PersonParticipation(pp_id={self.pp_id!r}, pt_id={self.pt_id!r}, tt_id={self.tt_id!r})>"
