# app/models/role_permissions.py
from sqlalchemy import Column, Text, ForeignKey, text
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import relationship
import uuid

from app.db.base_class import Base


class RolePermissions(Base):
    """
    SQLAlchemy model for role_permissions (role_permissions) table.

    Columns:
      - role_permission_id   : uuid, not null, default uuid_generate_v4()
      - role_id  : uuid, not null (FK -> roles.role_id)
      - permission_id     : uuid, not null (FK -> permissions.permission_id)
    """

    __tablename__ = "role_permissions"

    role_permission_id = Column(
        UUID(as_uuid=True),
        primary_key=True,
        nullable=False,
        server_default=text("uuid_generate_v4()"),
        doc="Primary key UUID (generated by Postgres uuid_generate_v4())",
    )

    role_id = Column(
        UUID(as_uuid=True),
        ForeignKey("roles.role_id", ondelete="CASCADE"),
        nullable=False,
        doc="FK to roles.role_id",
    )

    permission_id = Column(
        UUID(as_uuid=True),
        ForeignKey("permissions.permission_id", ondelete="CASCADE"),
        nullable=False,
        doc="FK to permissions.permission_id",
    )

    # -------------
    # Relationships
    # -------------
    
    role = relationship("Role", back_populates="role_permission")
    permission = relationship("Permissions", back_populates="role_permission")

    def __repr__(self) -> str:
        return (
            f"<RolePermissions(role_permission_id={self.role_permission_id!r}, role_id={self.role_id!r}, "
            f"permission_id={self.permission_id!r})>"
        )
