from sqlalchemy import Column, Text, text
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import relationship
import uuid

from app.db.base_class import Base


class Sport(Base):
    """
    SQLAlchemy model for the sport table.

    Matches table columns:
      - sport_id   : uuid, not null, default uuid_generate_v4()
      - sport_name : text, not null, unique
    """

    __tablename__ = "sport"  # change to "sports" if your DB table is named "sports"

    # UUID primary key, uses Postgres server-side generator uuid_generate_v4().
    # Note: ensure the uuid-ossp extension is enabled (or change to gen_random_uuid()).
    sport_id = Column(
        UUID(as_uuid=True),
        primary_key=True,
        nullable=False,
        server_default=text("uuid_generate_v4()"),
        doc="Primary key UUID (generated by Postgres uuid_generate_v4())",
    )

    # Sport name, text, not-null, unique constraint
    sport_name = Column(
        Text(),
        nullable=False,
        unique=True,
        doc="Unique sport name",
    )

    # ----------------------
    # RELATIONSHIPS
    # ----------------------

    actions = relationship(
        "Action",
        back_populates="sport",
        cascade="all, delete-orphan",
        passive_deletes=True,
    )

    tournaments = relationship(
        "Tournament",
        back_populates="sport",
        cascade="all, delete-orphan",
        passive_deletes=True,
    )

    # Relationships
    teams = relationship("Team", back_populates="sport")

    def __repr__(self) -> str:
        return f"<Sport(sport_id={self.sport_id!r}, sport_name={self.sport_name!r})>"
