# app/models/team_tournament.py
from sqlalchemy import Column, ForeignKey, text
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import relationship
import uuid

from app.db.base_class import Base


class TeamTournament(Base):
    """
    SQLAlchemy model for team_tournament table.

    Columns:
      - tt_id         : uuid, not null, default uuid_generate_v4()
      - team_id       : uuid, not null (FK -> team.team_id)
      - tournament_id : uuid, not null (FK -> tournament.tournament_id)
    """

    __tablename__ = "team_tournament"

    tt_id = Column(
        UUID(as_uuid=True),
        primary_key=True,
        nullable=False,
        server_default=text("uuid_generate_v4()"),
        doc="Primary key UUID (generated by Postgres uuid_generate_v4())",
    )

    team_id = Column(
        UUID(as_uuid=True),
        ForeignKey("team.team_id", ondelete="CASCADE"),
        nullable=False,
        doc="FK to team.team_id",
    )

    tournament_id = Column(
        UUID(as_uuid=True),
        ForeignKey("tournament.tournament_id", ondelete="CASCADE"),
        nullable=False,
        doc="FK to tournament.tournament_id",
    )

    # Relationships
    team = relationship("Team", back_populates="team_tournaments")
    tournament = relationship("Tournament", back_populates="team_tournaments")

    person_participations = relationship(
        "PersonParticipation",
        back_populates="team_tournament",
        cascade="all, delete-orphan"
    )

    def __repr__(self) -> str:
        return (
            f"<TeamTournament(tt_id={self.tt_id!r}, team_id={self.team_id!r}, "
            f"tournament_id={self.tournament_id!r})>"
        )
