# app/models/user_roles.py
from sqlalchemy import Column, Text, ForeignKey, text
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import relationship
import uuid

from app.db.base_class import Base


class UserRoles(Base):
    """
    SQLAlchemy model for user_roles (user_roles) table.

    Columns:
      - user_role_id   : uuid, not null, default uuid_generate_v4()
      - user_id  : uuid, not null (FK -> users.user_id)
      - role_id  : uuid, not null (FK -> roles.role_id)
      - organization_id     : uuid, not null (FK -> organization.organization_id)
    """

    __tablename__ = "user_roles"

    user_role_id = Column(
        UUID(as_uuid=True),
        primary_key=True,
        nullable=False,
        server_default=text("uuid_generate_v4()"),
        doc="Primary key UUID (generated by Postgres uuid_generate_v4())",
    )

    user_id = Column(
        UUID(as_uuid=True),
        ForeignKey("users.user_id", ondelete="CASCADE"),
        nullable=False,
        doc="FK to users.user_id",
    )

    role_id = Column(
        UUID(as_uuid=True),
        ForeignKey("roles.role_id", ondelete="CASCADE"),
        nullable=False,
        doc="FK to roles.role_id",
    )

    organization_id = Column(
        UUID(as_uuid=True),
        ForeignKey("organization.organization_id", ondelete="CASCADE"),
        nullable=False,
        doc="FK to organization.organization_id",
    )

    # -------------
    # Relationships
    # -------------
    
    users = relationship("User", back_populates="user_role")
    role = relationship("Role", back_populates="user_role")
    organization = relationship("Organization", back_populates="user_role")

    def __repr__(self) -> str:
        return (
            f"<UserRoles(user_role_id={self.user_role_id!r}, user_id={self.user_id!r}, "
            f"role_id={self.role_id!r}, organization_id={self.organization_id!r})>"
        )
